### ISSUE TITLE
Through calculation seem to be wrong

### ISSUE THREAD

**Issue by mentels** [erlanglab/erlangpl#7]
Either I'm not getting or the message throughput is calculated/presented incorrectly. Look at the screenshots: the number says it ~200 while the graph show ~100.
<img width="921" alt="screen shot 2017-03-01 at 17 28 45" src="https://cloud.githubusercontent.com/assets/748608/23469780/e3e8a2dc-fea4-11e6-80f8-7d2cdaf76eb6.png">
<img width="911" alt="screen shot 2017-03-01 at 17 28 50" src="https://cloud.githubusercontent.com/assets/748608/23469779/e371312a-fea4-11e6-85ff-d1c60bdd69b2.png">
<img width="923" alt="screen shot 2017-03-01 at 17 28 54" src="https://cloud.githubusercontent.com/assets/748608/23469778/e3536e10-fea4-11e6-85bc-474af80c8daf.png">

**Comment by michalslaski** [comment]
Thanks for reporting. The chart is a fake at the moment. It was added to dashboard just to give an idea of possible layout of this view. A new UI is being implemented in https://github.com/erlanglab/erlangpl-ui, where charts are real.

Please feel free to send a PR, if you would like the charts to be fixed in the old UI.
